server:
  port: 7003

spring:
  application:
    name: eureka7003

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7002:7002/eureka, http://eureka7004:7004/eureka

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF